project:
  debug: true
  json_serializer: default
  replace_non_json_serializable: true
  performance_logging: false
  register_workflow: true
  enrich_messages: true
  telemetry_capture:
    gpu: true
    cpu: true
    per_cpu: true
    process_info: true
    mem: true
    disk: true
    network: true
    machine_info: true
log:
  log_path: flowcept.log
  log_file_level: debug
  log_stream_level: debug
experiment:
  user: souzar
  experiment_id: testao
main_redis:
  host: localhost
  port: 6379
  channel: interception
  buffer_size: 50
  insertion_buffer_time_secs: 5
mongodb:
  host: login13
  port: 27017
  db: flowcept
  collection: tasks
  insertion_buffer_time_secs: 5
  max_buffer_size: 50
  min_buffer_size: 10
  remove_empty_fields: false
  create_collection_index: true
web_server:
  host: 0.0.0.0
  port: 5000
extra_metadata:
  place_holder: ''
  job_id: 123456
analytics:
  sort_orders:
    generated.loss: minimum_first
    generated.accuracy: maximum_first
adapters:
  dask:
    kind: dask
    redis_host: localhost
    redis_port: localhost
    worker_should_get_input: true
    scheduler_should_get_input: true
    worker_should_get_output: true
    scheduler_create_timestamps: true
    worker_create_timestamps: false
