name: Release and Publish
on:
  push:  # It has to be push, otherwise error happens in code below.
    branches: [ "main" ]
    #branches: [ "main", "dev" ] # use this only to test the CI
    #branches: [ "disabled" ]
jobs:
  build:
    name: Create Release and Publish
    runs-on: ubuntu-latest
#    env:
#      FLOWCEPT_SETTINGS_PATH: 'resources/settings.yaml'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          verbose: true
      - name: Publish distribution to PyPI
        #if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
      - name: Wait pypi do its thing
        run: sleep 120
      - name: Test pip install
        run: pip install cluster_experiment_utils
